package com.orinuno.repository;

import com.orinuno.model.KodikCalendarOutboxEvent;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * MyBatis mapper for {@code kodik_calendar_outbox} (CAL-6). Append-only: callers insert events
 * after detecting deltas; readers replay by {@code detected_at} watermark or by {@code
 * shikimori_id}.
 */
@Mapper
public interface KodikCalendarOutboxRepository {

    /**
     * Append one event. {@code id} is generated by the database — caller does not need to set it.
     */
    void insert(@Param("event") KodikCalendarOutboxEvent event);

    /**
     * Replay events newer than {@code since} (exclusive), ordered ascending, capped by {@code
     * limit}.
     */
    List<KodikCalendarOutboxEvent> findSince(
            @Param("since") LocalDateTime since, @Param("limit") int limit);

    /** All events for one anime, oldest first. */
    List<KodikCalendarOutboxEvent> findByShikimoriId(@Param("shikimoriId") String shikimoriId);

    /** Total event count — used by the health endpoint. */
    long countAll();
}
