package com.orinuno.mapper;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.orinuno.contract.source.ContentKindHint;
import com.orinuno.contract.source.ExternalIds;
import com.orinuno.contract.source.Provenance;
import com.orinuno.contract.source.SourceCatalogEvent;
import com.orinuno.contract.source.SourceContentInfo;
import com.orinuno.contract.source.SourceEpisode;
import com.orinuno.contract.source.SourceEpisodeVariant;
import com.orinuno.contract.source.SourceIdentifier;
import com.orinuno.contract.source.SourceSeason;
import com.orinuno.model.KodikContent;
import com.orinuno.model.KodikEpisodeVariant;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import lombok.extern.slf4j.Slf4j;

/**
 * Renders L1 Kodik state ({@link KodikContent} + decoded {@link KodikEpisodeVariant}s) into a
 * producer-side {@link SourceCatalogEvent} suitable for exposure on the wire to the external
 * aggregator's {@code external bridge} and other open consumers. Stage B of ARCH-0017.
 *
 * <p>Mapping decisions:
 *
 * <ul>
 *   <li><b>Identifier</b>: {@code SourceIdentifier.of("kodik", String.valueOf(content.getId()))}.
 *       The orinuno PK is used (not {@code kodikId}) to preserve the existing meter deduplication
 *       key — meter records today carry numeric source ids generated by orinuno's auto-increment
 *       column.
 *   <li><b>Movie vs series</b>: same whitelist as {@code downstream consumer}'s {@code
 *       KodikMeterMapper} ({@code movie} / {@code foreign-movie} / {@code soviet-cartoon} / {@code
 *       cartoon}).
 *   <li><b>Variant filter</b>: only variants with a non-blank {@code mp4Link} are surfaced.
 *       Episodes without playable variants are dropped, empty seasons are dropped. If everything is
 *       dropped the title falls back to {@link SourceCatalogEvent.TitleObserved} so consumers still
 *       see the chrome.
 *   <li><b>Provenance</b>: {@code sourceUrl=orinuno-app://kodik/<kodikId>}, {@code fetchedAt} from
 *       {@code content.updatedAt} when available, otherwise the supplied clock. Mirrors the
 *       producer-side discipline used by {@code KodikCatalogIngestion}.
 *   <li><b>Posters</b> (ARCH-0017-FOLLOWUP-POSTER): {@link SourceContentInfo#posterUrl()} comes
 *       from {@code material_data.poster_url_original} with fallbacks to {@code poster_url} /
 *       {@code anime_poster_url} / {@code drama_poster_url}; {@link
 *       SourceContentInfo#bigPosterUrl()} is the original-sized variant only; {@link
 *       SourceContentInfo#screenshotUrls()} is the {@code screenshots} JSON array. {@link
 *       SourceContentInfo#trailerUrls()} stays empty — Kodik does not expose trailer URLs in its L1
 *       schema.
 * </ul>
 */
@Slf4j
public final class SourceEventMapper {

    private static final String SOURCE_TYPE = "kodik";
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private SourceEventMapper() {}

    public static SourceCatalogEvent toEvent(
            KodikContent content, List<KodikEpisodeVariant> variants, Clock clock) {
        SourceIdentifier identifier =
                SourceIdentifier.of(SOURCE_TYPE, String.valueOf(content.getId()));
        SourceContentInfo info = buildInfo(content);
        Provenance provenance = buildProvenance(content, clock);

        List<KodikEpisodeVariant> playable =
                variants.stream()
                        .filter(v -> v.getMp4Link() != null && !v.getMp4Link().isBlank())
                        .toList();

        if (playable.isEmpty()) {
            return new SourceCatalogEvent.TitleObserved(identifier, info, provenance);
        }

        if (isMovie(content.getType())) {
            SourceEpisodeVariant variant = toVariant(playable.get(0));
            return new SourceCatalogEvent.MovieDiscovered(identifier, info, variant, provenance);
        }

        List<SourceSeason> seasons = groupIntoSeasons(playable);
        if (seasons.isEmpty()) {
            return new SourceCatalogEvent.TitleObserved(identifier, info, provenance);
        }
        return new SourceCatalogEvent.SeriesDiscovered(identifier, info, seasons, provenance);
    }

    private static boolean isMovie(String type) {
        if (type == null) {
            return false;
        }
        String normalised = type.toLowerCase(Locale.ROOT);
        return normalised.equals("movie")
                || normalised.equals("foreign-movie")
                || normalised.equals("soviet-cartoon")
                || normalised.equals("cartoon");
    }

    private static SourceContentInfo buildInfo(KodikContent content) {
        Map<String, Object> materialData = parseMaterialData(content.getMaterialData());
        List<String> screenshotUrls = parseScreenshots(content.getScreenshots());
        return SourceContentInfo.builder()
                .titleRu(content.getTitle())
                .titleEn(content.getTitleOrig())
                .year(content.getYear())
                .kindHint(deriveKindHint(content.getType()))
                .externalIds(
                        ExternalIds.builder()
                                .kinopoiskId(content.getKinopoiskId())
                                .imdbId(content.getImdbId())
                                .shikimoriId(content.getShikimoriId())
                                .build())
                .posterUrl(extractPosterUrl(materialData))
                .bigPosterUrl(extractBigPosterUrl(materialData))
                .screenshotUrls(screenshotUrls)
                .build();
    }

    /**
     * Reads the {@code poster_url_original}/{@code poster_url}/{@code anime_poster_url}/{@code
     * drama_poster_url} fields from Kodik's {@code material_data} blob and returns the first
     * non-blank value. Mirrors {@link com.orinuno.mapper.ContentMapper#extractPosterUrl} but with
     * graceful fallbacks for the kind-specialised poster URLs that {@code KodikMaterialDataDto}
     * also exposes.
     */
    private static String extractPosterUrl(Map<String, Object> materialData) {
        if (materialData == null) {
            return null;
        }
        return firstNonBlank(
                materialData,
                "poster_url_original",
                "poster_url",
                "anime_poster_url",
                "drama_poster_url");
    }

    /**
     * Returns the original/largest poster URL when Kodik exposes one separately from the regular
     * {@code poster_url}. Falls back to {@code null} when only the regular variant is present —
     * consumers can promote {@link #extractPosterUrl} when they need a single best-effort URL.
     */
    private static String extractBigPosterUrl(Map<String, Object> materialData) {
        if (materialData == null) {
            return null;
        }
        return firstNonBlank(materialData, "poster_url_original");
    }

    private static String firstNonBlank(Map<String, Object> map, String... keys) {
        for (String key : keys) {
            Object value = map.get(key);
            if (value instanceof String s && !s.isBlank()) {
                return s;
            }
        }
        return null;
    }

    private static Map<String, Object> parseMaterialData(String json) {
        if (json == null || json.isBlank()) {
            return null;
        }
        try {
            return OBJECT_MAPPER.readValue(json, new TypeReference<>() {});
        } catch (JsonProcessingException e) {
            log.warn(
                    "SourceEventMapper: failed to parse material_data JSON, posters will be"
                            + " omitted: {}",
                    e.getMessage());
            return null;
        }
    }

    private static List<String> parseScreenshots(String json) {
        if (json == null || json.isBlank()) {
            return Collections.emptyList();
        }
        try {
            List<String> raw = OBJECT_MAPPER.readValue(json, new TypeReference<>() {});
            if (raw == null) {
                return Collections.emptyList();
            }
            List<String> sanitised = new ArrayList<>(raw.size());
            for (String s : raw) {
                if (s != null && !s.isBlank()) {
                    sanitised.add(s);
                }
            }
            return sanitised;
        } catch (JsonProcessingException e) {
            log.warn(
                    "SourceEventMapper: failed to parse screenshots JSON, screenshotUrls will be"
                            + " omitted: {}",
                    e.getMessage());
            return Collections.emptyList();
        }
    }

    private static ContentKindHint deriveKindHint(String type) {
        if (type == null) {
            return ContentKindHint.UNKNOWN;
        }
        String normalised = type.toLowerCase(Locale.ROOT);
        if (isMovie(normalised)) {
            return ContentKindHint.MOVIE;
        }
        if (normalised.contains("anime")) {
            return ContentKindHint.ANIME;
        }
        if (normalised.contains("serial")
                || normalised.contains("show")
                || normalised.contains("documentary")) {
            return ContentKindHint.SERIES;
        }
        return ContentKindHint.UNKNOWN;
    }

    private static Provenance buildProvenance(KodikContent content, Clock clock) {
        Instant fetchedAt =
                Optional.ofNullable(content.getUpdatedAt())
                        .map(ldt -> ldt.toInstant(ZoneOffset.UTC))
                        .orElse(Instant.now(clock));
        String sourceUrl =
                "orinuno-app://kodik/"
                        + Optional.ofNullable(content.getKodikId())
                                .orElse(String.valueOf(content.getId()));
        return Provenance.of(sourceUrl, fetchedAt);
    }

    private static List<SourceSeason> groupIntoSeasons(List<KodikEpisodeVariant> playable) {
        Map<Integer, Map<Integer, List<KodikEpisodeVariant>>> grouped = new LinkedHashMap<>();
        playable.stream()
                .sorted(
                        Comparator.comparingInt(
                                        (KodikEpisodeVariant v) ->
                                                Optional.ofNullable(v.getSeasonNumber()).orElse(0))
                                .thenComparingInt(
                                        v -> Optional.ofNullable(v.getEpisodeNumber()).orElse(0)))
                .forEach(
                        v ->
                                grouped.computeIfAbsent(
                                                Optional.ofNullable(v.getSeasonNumber()).orElse(0),
                                                k -> new LinkedHashMap<>())
                                        .computeIfAbsent(
                                                Optional.ofNullable(v.getEpisodeNumber()).orElse(0),
                                                k -> new java.util.ArrayList<>())
                                        .add(v));

        return grouped.entrySet().stream()
                .map(
                        seasonEntry -> {
                            List<SourceEpisode> episodes =
                                    seasonEntry.getValue().entrySet().stream()
                                            .map(
                                                    episodeEntry ->
                                                            new SourceEpisode(
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    null,
                                                                    episodeEntry.getKey(),
                                                                    episodeEntry.getValue().stream()
                                                                            .map(
                                                                                    SourceEventMapper
                                                                                            ::toVariant)
                                                                            .toList()))
                                            .toList();
                            return new SourceSeason(
                                    null, null, null, seasonEntry.getKey(), episodes);
                        })
                .toList();
    }

    private static SourceEpisodeVariant toVariant(KodikEpisodeVariant variant) {
        SourceIdentifier identifier =
                SourceIdentifier.of(SOURCE_TYPE, String.valueOf(variant.getId()));
        return new SourceEpisodeVariant(
                identifier,
                variant.getMp4Link(),
                variant.getTranslationTitle(),
                variant.getQuality(),
                null,
                null);
    }
}
